import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import merchantsRouter from "./merchants";
import transactionsRouter from "./transactions";
import withdrawalsRouter from "./withdrawals";
import apiKeysRouter from "./apiKeys";
import webhooksRouter from "./webhooks";
import callbacksRouter from "./callbacks";
import settlementsRouter from "./settlements";
import usersRouter from "./users";
import productsRouter from "./products";
import connectionsRouter from "./connections";
import plansRouter from "./plans";
import qrCodesRouter from "./qrCodes";
import virtualAccountsRouter from "./virtualAccounts";
import apiMonitoringRouter from "./apiMonitoring";
import auditLogsRouter from "./auditLogs";
import featureControlRouter from "./featureControl";
import accountDetailsRouter from "./accountDetails";
import invoicesRouter from "./invoices";
import ledgerRouter from "./ledger";
import providersRouter from "./providers";
import notificationsRouter from "./notifications";
import reconciliationRouter from "./reconciliation";
import paymentLinksRouter from "./paymentLinks";
import systemConfigRouter from "./systemConfig";
import settingsRouter from "./settings";
import storageRouter from "./storage";
import savedFiltersRouter from "./savedFilters";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/merchants", merchantsRouter);
router.use("/transactions", transactionsRouter);
router.use("/withdrawals", withdrawalsRouter);
router.use("/api-keys", apiKeysRouter);
router.use("/webhooks", webhooksRouter);
router.use("/callbacks", callbacksRouter);
router.use("/settlements", settlementsRouter);
router.use("/users", usersRouter);
router.use("/products", productsRouter);
router.use("/connections", connectionsRouter);
router.use("/plans", plansRouter);
router.use("/qr-codes", qrCodesRouter);
router.use("/virtual-accounts", virtualAccountsRouter);
router.use("/api-monitoring", apiMonitoringRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/feature-control", featureControlRouter);
router.use("/account-details", accountDetailsRouter);
router.use("/invoices", invoicesRouter);
router.use("/ledger", ledgerRouter);
router.use("/providers", providersRouter);
router.use("/notifications", notificationsRouter);
router.use("/reconciliation", reconciliationRouter);
router.use("/payment-links", paymentLinksRouter);
router.use("/system-config", systemConfigRouter);
router.use("/settings", settingsRouter);
router.use(storageRouter);
router.use("/saved-filters", savedFiltersRouter);

export default router;
