import { boolean, integer, jsonb, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const promotionalCampaignsTable = pgTable("promotional_campaigns", {
  id: serial("id").primaryKey(),
  internalName: text("internal_name").notNull(),
  publicTitle: text("public_title"),
  subtitle: text("subtitle"),
  description: text("description"),
  badge: text("badge"),
  ctaText: text("cta_text"),
  ctaUrl: text("cta_url"),
  secondaryCtaText: text("secondary_cta_text"),
  secondaryCtaUrl: text("secondary_cta_url"),
  desktopImageUrl: text("desktop_image_url"),
  tabletImageUrl: text("tablet_image_url"),
  mobileImageUrl: text("mobile_image_url"),
  videoUrl: text("video_url"),
  altText: text("alt_text"),
  type: text("type").notNull().default("text_banner"),
  theme: text("theme").default("dark"),
  backgroundColor: text("background_color"),
  gradientFrom: text("gradient_from"),
  gradientTo: text("gradient_to"),
  overlayOpacity: integer("overlay_opacity").default(40),
  animation: text("animation").default("fade"),
  placement: text("placement").notNull(),
  priority: integer("priority").default(0),
  displayOrder: integer("display_order").default(0),
  status: text("status").notNull().default("draft"),
  startAt: timestamp("start_at", { withTimezone: true }),
  endAt: timestamp("end_at", { withTimezone: true }),
  audience: text("audience").default("all"),
  deviceTargeting: text("device_targeting").default("all"),
  language: text("language").default("en"),
  autoplay: boolean("autoplay").default(true),
  slideSpeedMs: integer("slide_speed_ms").default(5000),
  infiniteLoop: boolean("infinite_loop").default(true),
  showNavArrows: boolean("show_nav_arrows").default(true),
  showDots: boolean("show_dots").default(true),
  pauseOnHover: boolean("pause_on_hover").default(true),
  countdownEndAt: timestamp("countdown_end_at", { withTimezone: true }),
  isSlotEnabled: boolean("is_slot_enabled").default(true),
  createdBy: integer("created_by"),
  updatedBy: integer("updated_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const promotionalAnalyticsTable = pgTable("promotional_analytics", {
  id: serial("id").primaryKey(),
  campaignId: integer("campaign_id").notNull(),
  eventType: text("event_type").notNull(),
  placement: text("placement"),
  deviceType: text("device_type"),
  sessionId: text("session_id"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
