import { pgTable, varchar, text, timestamp } from "drizzle-orm/pg-core";

export const systemConfigTable = pgTable("system_config", {
  key: varchar("key", { length: 100 }).primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  updatedByEmail: varchar("updated_by_email", { length: 255 }),
});

export type SystemConfig = typeof systemConfigTable.$inferSelect;

export const SYSTEM_CONFIG_KEYS = {
  RECONCILIATION_HOUR: "reconciliation_hour",
  RECONCILIATION_MINUTE: "reconciliation_minute",
  RECONCILIATION_LOOKBACK_DAYS: "reconciliation_lookback_days",
  RECONCILIATION_ENABLED: "reconciliation_enabled",
  QR_CLEANUP_RETENTION_DAYS: "qr_cleanup_retention_days",
  VA_CLEANUP_RETENTION_DAYS: "va_cleanup_retention_days",
  LEDGER_BACKFILL_LAST_RUN_AT: "ledger_backfill_last_run_at",
  LEDGER_BACKFILL_ROWS_UPDATED: "ledger_backfill_rows_updated",
  SIGNATURE_FAILURE_ALERT_THRESHOLD: "signature_failure_alert_threshold",
  SIGNATURE_FAILURE_ALERT_COOLDOWN_HOURS: "signature_failure_alert_cooldown_hours",
  WEBHOOK_RETRY_MAX_ATTEMPTS: "webhook_retry_max_attempts",
  WEBHOOK_RETRY_DELAY_1: "webhook_retry_delay_1",
  WEBHOOK_RETRY_DELAY_2: "webhook_retry_delay_2",
  WEBHOOK_RETRY_DELAY_3: "webhook_retry_delay_3",
  TEST_EMAIL_HISTORY_RETENTION_DAYS: "test_email_history_retention_days",
  AUDIT_REPORT_LOG_RETENTION_DAYS: "audit_report_log_retention_days",
  QR_CLEANUP_LAST_RUN_AT: "qr_cleanup_last_run_at",
  QR_CLEANUP_LAST_RUN_DELETED: "qr_cleanup_last_run_deleted",
  AUDIT_REPORT_CLEANUP_LAST_RUN_AT: "audit_report_cleanup_last_run_at",
  AUDIT_REPORT_CLEANUP_LAST_RUN_DELETED: "audit_report_cleanup_last_run_deleted",
  VA_CLEANUP_LAST_RUN_AT: "va_cleanup_last_run_at",
  VA_CLEANUP_LAST_DELETED: "va_cleanup_last_deleted",
  EKQR_API_KEY: "ekqr_api_key",
  EKQR_ENABLED: "ekqr_enabled",
  EKQR_ENV: "ekqr_env",
  EKQR_WEBHOOK_SECRET: "ekqr_webhook_secret",
  WEBHOOK_FAILURE_ALERT_COOLDOWN_HOURS: "webhook_failure_alert_cooldown_hours",
  EKQR_SYNC_ENABLED: "ekqr_sync_enabled",
  EKQR_SYNC_STALE_MINUTES: "ekqr_sync_stale_minutes",
  EKQR_SYNC_STUCK_THRESHOLD: "ekqr_sync_stuck_threshold",
  EKQR_SYNC_ALERT_COOLDOWN_HOURS: "ekqr_sync_alert_cooldown_hours",
  EKQR_SYNC_LAST_RUN_AT: "ekqr_sync_last_run_at",
  EKQR_SYNC_LAST_SYNCED: "ekqr_sync_last_synced",
  EKQR_SYNC_LAST_STUCK: "ekqr_sync_last_stuck",
  CASHFREE_CLIENT_ID: "cashfree_client_id",
  CASHFREE_CLIENT_SECRET: "cashfree_client_secret",
  CASHFREE_ENV: "cashfree_env",
  CASHFREE_WEBHOOK_SECRET: "cashfree_webhook_secret",
  CASHFREE_ENABLED: "cashfree_enabled",
  CASHFREE_BASE_URL: "cashfree_base_url",
  CASHFREE_API_VERSION: "cashfree_api_version",
  CASHFREE_UPI_ENABLED: "cashfree_upi_enabled",
  CASHFREE_QR_ENABLED: "cashfree_qr_enabled",
  CASHFREE_PAYMENT_LINKS_ENABLED: "cashfree_payment_links_enabled",
  CASHFREE_MERCHANT_PAYIN_ENABLED: "cashfree_merchant_payin_enabled",
  CASHFREE_MIN_AMOUNT: "cashfree_min_amount",
  CASHFREE_MAX_AMOUNT: "cashfree_max_amount",
  CASHFREE_DAILY_LIMIT: "cashfree_daily_limit",
  CASHFREE_PAYOUT_CLIENT_ID: "cashfree_payout_client_id",
  CASHFREE_PAYOUT_CLIENT_SECRET: "cashfree_payout_client_secret",
  CASHFREE_PAYOUT_ENV: "cashfree_payout_env",
  CASHFREE_PAYOUT_ENABLED: "cashfree_payout_enabled",
  CASHFREE_PAYOUT_FUNDSOURCE_ID: "cashfree_payout_fundsource_id",
  CASHFREE_PAYOUT_BASE_URL: "cashfree_payout_base_url",
  CASHFREE_PAYOUT_API_VERSION: "cashfree_payout_api_version",
  CASHFREE_PAYOUT_WEBHOOK_SECRET: "cashfree_payout_webhook_secret",
  CASHFREE_PAYOUT_MERCHANT_ENABLED: "cashfree_payout_merchant_enabled",
  CASHFREE_PAYOUT_ADMIN_APPROVAL_REQUIRED: "cashfree_payout_admin_approval_required",
  CASHFREE_PAYOUT_MIN_LIMIT: "cashfree_payout_min_limit",
  CASHFREE_PAYOUT_MAX_LIMIT: "cashfree_payout_max_limit",
  CASHFREE_PAYOUT_DAILY_LIMIT: "cashfree_payout_daily_limit",
  CASHFREE_PAYOUT_BULK_ENABLED: "cashfree_payout_bulk_enabled",
  QUIET_HOURS_FLUSH_INTERVAL_SECONDS: "quiet_hours_flush_interval_seconds",
} as const;

export const SYSTEM_CONFIG_DEFAULTS = {
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_HOUR]: "0",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_MINUTE]: "0",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_LOOKBACK_DAYS]: "1",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.QR_CLEANUP_RETENTION_DAYS]: "30",
  [SYSTEM_CONFIG_KEYS.SIGNATURE_FAILURE_ALERT_THRESHOLD]: "10",
  [SYSTEM_CONFIG_KEYS.SIGNATURE_FAILURE_ALERT_COOLDOWN_HOURS]: "4",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_MAX_ATTEMPTS]: "4",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_1]: "300",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_2]: "900",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_3]: "3600",
  [SYSTEM_CONFIG_KEYS.TEST_EMAIL_HISTORY_RETENTION_DAYS]: "30",
  [SYSTEM_CONFIG_KEYS.AUDIT_REPORT_LOG_RETENTION_DAYS]: "90",
  [SYSTEM_CONFIG_KEYS.EKQR_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.EKQR_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_FAILURE_ALERT_COOLDOWN_HOURS]: "1",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_STALE_MINUTES]: "15",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_STUCK_THRESHOLD]: "10",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_ALERT_COOLDOWN_HOURS]: "4",
  [SYSTEM_CONFIG_KEYS.CASHFREE_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.CASHFREE_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_API_VERSION]: "2025-01-01",
  [SYSTEM_CONFIG_KEYS.CASHFREE_UPI_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_QR_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYMENT_LINKS_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MERCHANT_PAYIN_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MIN_AMOUNT]: "1",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MAX_AMOUNT]: "200000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_API_VERSION]: "2024-01-01",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MERCHANT_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ADMIN_APPROVAL_REQUIRED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MIN_LIMIT]: "100",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MAX_LIMIT]: "200000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_BULK_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.QUIET_HOURS_FLUSH_INTERVAL_SECONDS]: "60",
} as const;
