import { pgTable, varchar, text, timestamp } from "drizzle-orm/pg-core";

export const systemConfigTable = pgTable("system_config", {
  key: varchar("key", { length: 100 }).primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  updatedByEmail: varchar("updated_by_email", { length: 255 }),
});

export type SystemConfig = typeof systemConfigTable.$inferSelect;

export const SYSTEM_CONFIG_KEYS = {
  RECONCILIATION_HOUR: "reconciliation_hour",
  RECONCILIATION_MINUTE: "reconciliation_minute",
  RECONCILIATION_LOOKBACK_DAYS: "reconciliation_lookback_days",
  RECONCILIATION_ENABLED: "reconciliation_enabled",
  QR_CLEANUP_RETENTION_DAYS: "qr_cleanup_retention_days",
  VA_CLEANUP_RETENTION_DAYS: "va_cleanup_retention_days",
  LEDGER_BACKFILL_LAST_RUN_AT: "ledger_backfill_last_run_at",
  LEDGER_BACKFILL_ROWS_UPDATED: "ledger_backfill_rows_updated",
  SIGNATURE_FAILURE_ALERT_THRESHOLD: "signature_failure_alert_threshold",
  SIGNATURE_FAILURE_ALERT_COOLDOWN_HOURS: "signature_failure_alert_cooldown_hours",
  WEBHOOK_RETRY_MAX_ATTEMPTS: "webhook_retry_max_attempts",
  WEBHOOK_RETRY_DELAY_1: "webhook_retry_delay_1",
  WEBHOOK_RETRY_DELAY_2: "webhook_retry_delay_2",
  WEBHOOK_RETRY_DELAY_3: "webhook_retry_delay_3",
  TEST_EMAIL_HISTORY_RETENTION_DAYS: "test_email_history_retention_days",
  AUDIT_REPORT_LOG_RETENTION_DAYS: "audit_report_log_retention_days",
  QR_CLEANUP_LAST_RUN_AT: "qr_cleanup_last_run_at",
  QR_CLEANUP_LAST_RUN_DELETED: "qr_cleanup_last_run_deleted",
  AUDIT_REPORT_CLEANUP_LAST_RUN_AT: "audit_report_cleanup_last_run_at",
  AUDIT_REPORT_CLEANUP_LAST_RUN_DELETED: "audit_report_cleanup_last_run_deleted",
  VA_CLEANUP_LAST_RUN_AT: "va_cleanup_last_run_at",
  VA_CLEANUP_LAST_DELETED: "va_cleanup_last_deleted",
  EKQR_API_KEY: "ekqr_api_key",
  EKQR_ENABLED: "ekqr_enabled",
  EKQR_ENV: "ekqr_env",
  EKQR_WEBHOOK_SECRET: "ekqr_webhook_secret",
  EKQR_MIN_AMOUNT: "ekqr_min_amount",
  EKQR_MAX_AMOUNT: "ekqr_max_amount",
  EKQR_DAILY_LIMIT: "ekqr_daily_limit",
  WEBHOOK_FAILURE_ALERT_COOLDOWN_HOURS: "webhook_failure_alert_cooldown_hours",
  EKQR_SYNC_ENABLED: "ekqr_sync_enabled",
  EKQR_SYNC_STALE_MINUTES: "ekqr_sync_stale_minutes",
  EKQR_SYNC_STUCK_THRESHOLD: "ekqr_sync_stuck_threshold",
  EKQR_SYNC_ALERT_COOLDOWN_HOURS: "ekqr_sync_alert_cooldown_hours",
  EKQR_SYNC_LAST_RUN_AT: "ekqr_sync_last_run_at",
  EKQR_SYNC_LAST_SYNCED: "ekqr_sync_last_synced",
  EKQR_SYNC_LAST_STUCK: "ekqr_sync_last_stuck",
  UPIGATEWAY_PAYIN_ENABLED: "upigateway_payin_enabled",
  UPIGATEWAY_ENV: "upigateway_env",
  UPIGATEWAY_BASE_URL: "upigateway_base_url",
  UPIGATEWAY_API_KEY: "upigateway_api_key",
  UPIGATEWAY_WEBHOOK_SECRET: "upigateway_webhook_secret",
  UPIGATEWAY_MERCHANT_ID: "upigateway_merchant_id",
  UPIGATEWAY_CREATE_ORDER_ENDPOINT: "upigateway_create_order_endpoint",
  UPIGATEWAY_CHECK_STATUS_ENDPOINT: "upigateway_check_status_endpoint",
  UPIGATEWAY_MIN_AMOUNT: "upigateway_min_amount",
  UPIGATEWAY_MAX_AMOUNT: "upigateway_max_amount",
  UPIGATEWAY_MERCHANT_ACCESS: "upigateway_merchant_access",
  CASHFREE_CLIENT_ID: "cashfree_client_id",
  CASHFREE_CLIENT_SECRET: "cashfree_client_secret",
  CASHFREE_ENV: "cashfree_env",
  CASHFREE_WEBHOOK_SECRET: "cashfree_webhook_secret",
  CASHFREE_ENABLED: "cashfree_enabled",
  CASHFREE_BASE_URL: "cashfree_base_url",
  CASHFREE_API_VERSION: "cashfree_api_version",
  CASHFREE_UPI_ENABLED: "cashfree_upi_enabled",
  CASHFREE_QR_ENABLED: "cashfree_qr_enabled",
  CASHFREE_PAYMENT_LINKS_ENABLED: "cashfree_payment_links_enabled",
  CASHFREE_MERCHANT_PAYIN_ENABLED: "cashfree_merchant_payin_enabled",
  CASHFREE_MIN_AMOUNT: "cashfree_min_amount",
  CASHFREE_MAX_AMOUNT: "cashfree_max_amount",
  CASHFREE_DAILY_LIMIT: "cashfree_daily_limit",
  CASHFREE_PAYOUT_CLIENT_ID: "cashfree_payout_client_id",
  CASHFREE_PAYOUT_CLIENT_SECRET: "cashfree_payout_client_secret",
  CASHFREE_PAYOUT_ENV: "cashfree_payout_env",
  CASHFREE_PAYOUT_ENABLED: "cashfree_payout_enabled",
  CASHFREE_PAYOUT_FUNDSOURCE_ID: "cashfree_payout_fundsource_id",
  CASHFREE_PAYOUT_BASE_URL: "cashfree_payout_base_url",
  CASHFREE_PAYOUT_API_VERSION: "cashfree_payout_api_version",
  CASHFREE_PAYOUT_WEBHOOK_SECRET: "cashfree_payout_webhook_secret",
  CASHFREE_PAYOUT_MERCHANT_ENABLED: "cashfree_payout_merchant_enabled",
  CASHFREE_PAYOUT_ADMIN_APPROVAL_REQUIRED: "cashfree_payout_admin_approval_required",
  CASHFREE_PAYOUT_MIN_LIMIT: "cashfree_payout_min_limit",
  CASHFREE_PAYOUT_MAX_LIMIT: "cashfree_payout_max_limit",
  CASHFREE_PAYOUT_DAILY_LIMIT: "cashfree_payout_daily_limit",
  CASHFREE_PAYOUT_BULK_ENABLED: "cashfree_payout_bulk_enabled",
  QUIET_HOURS_FLUSH_INTERVAL_SECONDS: "quiet_hours_flush_interval_seconds",
  CREDENTIAL_ROTATION_EXTRA_RECIPIENTS: "credential_rotation_extra_recipients",
  // Global auto-payout approval settings (all default OFF for safety)
  AUTO_PAYOUT_GLOBAL_ENABLED: "auto_payout_global_enabled",
  AUTO_PAYOUT_GLOBAL_PAUSED: "auto_payout_global_paused",
  AUTO_PAYOUT_DEFAULT_MAX_SINGLE_AMOUNT: "auto_payout_default_max_single_amount",
  AUTO_PAYOUT_DEFAULT_DAILY_LIMIT: "auto_payout_default_daily_limit",
  AUTO_PAYOUT_DEFAULT_MONTHLY_LIMIT: "auto_payout_default_monthly_limit",
  AUTO_PAYOUT_DEFAULT_ALLOWED_MODES: "auto_payout_default_allowed_modes",
  AUTO_PAYOUT_DEFAULT_MIN_WALLET_BALANCE: "auto_payout_default_min_wallet_balance",
  // Payout wallet load settings
  WALLET_LOAD_ENABLED:           "wallet_load_enabled",
  WALLET_LOAD_ONLINE_ENABLED:    "wallet_load_online_enabled",
  WALLET_LOAD_MANUAL_UTR_ENABLED: "wallet_load_manual_utr_enabled",
  WALLET_LOAD_ADMIN_TOPUP_ENABLED: "wallet_load_admin_topup_enabled",
  WALLET_LOAD_MIN_AMOUNT:        "wallet_load_min_amount",
  WALLET_LOAD_MAX_AMOUNT:        "wallet_load_max_amount",
  WALLET_LOAD_FEE_TYPE:          "wallet_load_fee_type",   // NONE | FLAT | PERCENTAGE
  WALLET_LOAD_FEE_VALUE:         "wallet_load_fee_value",
  WALLET_LOAD_GST_ON_FEE:        "wallet_load_gst_on_fee",
  WALLET_LOAD_REQUIRE_SCREENSHOT: "wallet_load_require_screenshot",
  WALLET_LOAD_BANK_NAME:         "wallet_load_bank_name",
  WALLET_LOAD_ACCOUNT_NUMBER:    "wallet_load_account_number",
  WALLET_LOAD_IFSC:              "wallet_load_ifsc",
  WALLET_LOAD_ACCOUNT_HOLDER:    "wallet_load_account_holder",
  WALLET_LOAD_UPI_ID:            "wallet_load_upi_id",
  // Set when the payin smart-routing chain becomes fully exhausted (all
  // gateways failing); value is the ISO timestamp the outage started.
  // Cleared as soon as a routing attempt succeeds again, which also
  // triggers a "gateways are back online" notification to affected merchants.
  PAYIN_CHAIN_EXHAUSTED_SINCE: "payin_chain_exhausted_since",
  // Failover-exhaustion admin alert tuning
  FAILOVER_ALERT_THRESHOLD: "failover_alert_threshold",
  FAILOVER_ALERT_WINDOW_MINUTES: "failover_alert_window_minutes",
  // Razorpay Payin — credentials are ENV-ONLY, never stored here
  RAZORPAY_ENABLED:    "razorpay_enabled",
  RAZORPAY_MIN_AMOUNT: "razorpay_min_amount",
  RAZORPAY_MAX_AMOUNT: "razorpay_max_amount",
  RAZORPAY_DAILY_LIMIT: "razorpay_daily_limit",
  // Suspension flags — set to "true" to block all new live transactions for the provider.
  // Webhooks, status syncs, and read operations continue normally.
  // Cleared only by explicit admin DB update; server restarts do not revert the flag.
  CASHFREE_PAYIN_SUSPENDED:  "cashfree_payin_suspended",
  CASHFREE_PAYOUT_SUSPENDED: "cashfree_payout_suspended",
  // PayU Hosted Checkout — UAT only until provider activates payment modes
  // Credentials stored encrypted in provider_integrations table (never in system_config).
  PAYU_ENABLED:    "payu_enabled",
  PAYU_ENV:        "payu_env",        // "uat" | "live"
  PAYU_SUSPENDED:  "payu_suspended",
  PAYU_MIN_AMOUNT: "payu_min_amount",
  PAYU_MAX_AMOUNT: "payu_max_amount",
  PAYU_DAILY_LIMIT: "payu_daily_limit",
} as const;

export const SYSTEM_CONFIG_DEFAULTS = {
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_HOUR]: "0",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_MINUTE]: "0",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_LOOKBACK_DAYS]: "1",
  [SYSTEM_CONFIG_KEYS.RECONCILIATION_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.QR_CLEANUP_RETENTION_DAYS]: "30",
  [SYSTEM_CONFIG_KEYS.SIGNATURE_FAILURE_ALERT_THRESHOLD]: "10",
  [SYSTEM_CONFIG_KEYS.SIGNATURE_FAILURE_ALERT_COOLDOWN_HOURS]: "4",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_MAX_ATTEMPTS]: "4",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_1]: "300",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_2]: "900",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_RETRY_DELAY_3]: "3600",
  [SYSTEM_CONFIG_KEYS.TEST_EMAIL_HISTORY_RETENTION_DAYS]: "30",
  [SYSTEM_CONFIG_KEYS.AUDIT_REPORT_LOG_RETENTION_DAYS]: "90",
  [SYSTEM_CONFIG_KEYS.EKQR_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.EKQR_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.EKQR_MIN_AMOUNT]: "1",
  [SYSTEM_CONFIG_KEYS.EKQR_MAX_AMOUNT]: "200000",
  [SYSTEM_CONFIG_KEYS.EKQR_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.WEBHOOK_FAILURE_ALERT_COOLDOWN_HOURS]: "1",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_STALE_MINUTES]: "15",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_STUCK_THRESHOLD]: "10",
  [SYSTEM_CONFIG_KEYS.EKQR_SYNC_ALERT_COOLDOWN_HOURS]: "4",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_PAYIN_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_BASE_URL]: "https://api.ekqr.in",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_CREATE_ORDER_ENDPOINT]: "/api/create_order",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_CHECK_STATUS_ENDPOINT]: "/api/check_order_status",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_MIN_AMOUNT]: "1",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_MAX_AMOUNT]: "200000",
  [SYSTEM_CONFIG_KEYS.UPIGATEWAY_MERCHANT_ACCESS]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.CASHFREE_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_API_VERSION]: "2025-01-01",
  [SYSTEM_CONFIG_KEYS.CASHFREE_UPI_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_QR_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYMENT_LINKS_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MERCHANT_PAYIN_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MIN_AMOUNT]: "1",
  [SYSTEM_CONFIG_KEYS.CASHFREE_MAX_AMOUNT]: "200000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ENV]: "test",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_API_VERSION]: "2024-01-01",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MERCHANT_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_ADMIN_APPROVAL_REQUIRED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MIN_LIMIT]: "100",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_MAX_LIMIT]: "200000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_BULK_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYIN_SUSPENDED]:  "false",
  [SYSTEM_CONFIG_KEYS.CASHFREE_PAYOUT_SUSPENDED]: "false",
  [SYSTEM_CONFIG_KEYS.QUIET_HOURS_FLUSH_INTERVAL_SECONDS]: "60",
  [SYSTEM_CONFIG_KEYS.CREDENTIAL_ROTATION_EXTRA_RECIPIENTS]: "",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_GLOBAL_ENABLED]: "false",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_GLOBAL_PAUSED]: "false",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_DEFAULT_MAX_SINGLE_AMOUNT]: "10000",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_DEFAULT_DAILY_LIMIT]: "50000",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_DEFAULT_MONTHLY_LIMIT]: "500000",
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_DEFAULT_ALLOWED_MODES]: '["IMPS","NEFT","RTGS","UPI"]',
  [SYSTEM_CONFIG_KEYS.AUTO_PAYOUT_DEFAULT_MIN_WALLET_BALANCE]: "0",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_ENABLED]:           "true",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_ONLINE_ENABLED]:    "true",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_MANUAL_UTR_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_ADMIN_TOPUP_ENABLED]: "true",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_MIN_AMOUNT]:        "100",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_MAX_AMOUNT]:        "500000",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_FEE_TYPE]:          "NONE",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_FEE_VALUE]:         "0",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_GST_ON_FEE]:        "false",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_REQUIRE_SCREENSHOT]: "false",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_BANK_NAME]:         "",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_ACCOUNT_NUMBER]:    "",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_IFSC]:              "",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_ACCOUNT_HOLDER]:    "",
  [SYSTEM_CONFIG_KEYS.WALLET_LOAD_UPI_ID]:            "",
  [SYSTEM_CONFIG_KEYS.FAILOVER_ALERT_THRESHOLD]:       "5",
  [SYSTEM_CONFIG_KEYS.FAILOVER_ALERT_WINDOW_MINUTES]:  "60",
  [SYSTEM_CONFIG_KEYS.RAZORPAY_ENABLED]:    "false",
  [SYSTEM_CONFIG_KEYS.RAZORPAY_MIN_AMOUNT]: "100",
  [SYSTEM_CONFIG_KEYS.RAZORPAY_MAX_AMOUNT]: "500000",
  [SYSTEM_CONFIG_KEYS.RAZORPAY_DAILY_LIMIT]: "1000000",
  [SYSTEM_CONFIG_KEYS.PAYU_ENABLED]:    "false",
  [SYSTEM_CONFIG_KEYS.PAYU_ENV]:        "uat",
  [SYSTEM_CONFIG_KEYS.PAYU_SUSPENDED]:  "false",
  [SYSTEM_CONFIG_KEYS.PAYU_MIN_AMOUNT]: "1",
  [SYSTEM_CONFIG_KEYS.PAYU_MAX_AMOUNT]: "200000",
  [SYSTEM_CONFIG_KEYS.PAYU_DAILY_LIMIT]: "1000000",
} as const;
